### ISSUE TITLE
Broken hyperlink

### ISSUE THREAD

**Issue by ponnet** [hadley/mastering-shiny#105]
This one:
https://mastering-shiny.org/testing-overview.html

**Comment by hadley** [comment]
What page did you find that on

**Comment by ponnet** [comment]
18.3 Testing
Developing a test plan for an application is critical to ensure its ongoing stability. Without a test plan, every change jeopardizes the application. When the application is small enough that a single developer can internalize all of the inner-workings in their head, they may feel that there’s no need for an additional test plan. However, as soon as that developer steps away from the application for long enough to forget some piece of it, or when another developer needs to contribute to the application, the lack of a test plan will be felt acutely.

A testing plan could be entirely manual. A simple text file that lists all of the operations in the application that need to be tested in order to confirm that a new version of an application is correct would constitute a valid test plan and is a great place to start. However, you’ll likely find that the test plan will grow as the application becomes more complex. You’ll either spend more and more of your time manually testing the application or you’ll start skipping some of the tests with some releases which will eventually come back to bite you. Most applications rely on some combination of automated testing and manual testing; whether or not a test is worth automating comes down to how long you expect to spend manually testing versus how long it would take to automate.

For that reason, various forms of automated testing have been developed for Shiny, as outlined in the testing overview article. As that article explains, you can develop:

**Comment by ponnet** [comment]
Second to last sentence is hyperlinked

**Comment by hadley** [comment]
Can you please provide a link to the page where you found the broken link?

**Comment by ponnet** [comment]
Yes, sure :)
https://mastering-shiny.org/

**Comment by batpigandme** [comment]
Here's the line in the source Rmd
https://github.com/hadley/mastering-shiny/blob/fc64972f86f08288d6556c301fe916fc052a8c89/prod-best-practices.Rmd#L64

**Comment by hadley** [comment]
Looks like this link no longer exists
