### ISSUE TITLE
Gender selector app text input prevents changing radio button selection

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [hadley/mastering-shiny#118]
In this app if you add some text to the textInput, you can't then select another button without first deleting the text. Is this intentional? Fixing this would add a few more lines of code so I wasn't sure if you were trying to keep the example short.

https://github.com/hadley/mastering-shiny/blob/dc2bf863ea37916e97a00648482b7440117d18b7/action-modules.Rmd#L481

**Comment by mpaulacaldas** [comment]
I also encountered this issue, although not in the line that Mine points to, but in the code chunk that comes right afterwards (the one with the module). The issue should be fixed with https://github.com/hadley/mastering-shiny/pull/138
