### ISSUE TITLE
Chapter 2 excerise 5 solution

### ISSUE THREAD

**Issue by Danieldavid521** [hadley/mastering-shiny#130]
I can't seem to get this solution to work, I have found the 2 of the 3 supposed bugs, but I was wondering if maybe there is another error in the code before it is published,  I have been working on it for atleast a week, here is my github if you can help with a solution. Thank you `https://github.com/Danieldavid521/Mastering_Shiny_solutions/blob/master/Mastering_Shiny_Chapter_2-5_solutions.R`

**Comment by hadley** [comment]
If you're going to ask a question in multiple places, please have the courtesy to link them to one another: https://community.rstudio.com/t/mastering-shiny-chapter-2-exercise-5/49787/2
