### ISSUE TITLE
github actions build

### ISSUE THREAD

**Issue by EmilHvitfeldt** [hadley/mastering-shiny#131]
Hey @jimhester & @hadley.

I think I know why it doesn't deploy to Netlify in the recent commits.

I was trying to get this set up for our bookdown site the other day https://github.com/EmilHvitfeldt/tidy-nlp-in-R-book and I found that I needed to also run `netlify link ...`

https://github.com/EmilHvitfeldt/tidy-nlp-in-R-book/blob/2d9ef328f4c7a52a0e6383aaef120a5ace26be30/.github/workflows/bookdown.yaml#L45-L52

Could that be what you needed?

I also wrote a [post](https://www.hvitfeldt.me/blog/bookdown-netlify-github-actions/) detailing the process with a sample repository https://github.com/EmilHvitfeldt/bookdown-github-actions-netlify

**Comment by hadley** [comment]
I just went back to what travis did, i.e. an env var: https://github.com/hadley/mastering-shiny/commit/50974d1fe1daf90f640404bb1e2c26fb493ef660

**Comment by hadley** [comment]
(I'm not arguing that's the better approach, it's just what I did before so it was easier for me to recreate)
