### ISSUE TITLE
Problems in tibble prints

### ISSUE THREAD

**Issue by EmilHvitfeldt** [hadley/mastering-shiny#132]
<img width="794" alt="Screen Shot 2020-01-23 at 3 56 34 PM" src="https://user-images.githubusercontent.com/14034784/73034152-03e96580-3df9-11ea-9c6f-143fa4df4d1f.png">

Appears to be related to change to Github Actions https://github.com/hadley/mastering-shiny/commit/1bcd54b5d9542bfc90c3fa0a63c321b450ad64bb.

We are having similar problems after converting https://github.com/EmilHvitfeldt/tidy-nlp-in-R-book/issues/33

**Comment by hadley** [comment]
cc @jimhester

**Comment by jimhester** [comment]
The setup-r action sets [`crayon.enabled` to TRUE](https://github.com/r-lib/actions/blob/3ab3e728f902d8a1605ce7c17925624aa91837ba/setup-r/action.yml#L14-L16) by default. If you don't want this you can set it to `FALSE`

**Comment by hadley** [comment]
That manually forces colouring so the logs look nice? And then the usually checks for markdown get overridden?

**Comment by jimhester** [comment]
yeah.

We could add an option or envvar to revdepcheck, so we could just enable color only for that...

**Comment by hadley** [comment]
Fixed in https://github.com/hadley/mastering-shiny/commit/0b3681eefccb550fb0f2b1771e85142f132da4d6
