### ISSUE TITLE
Other UI toolkits

### ISSUE THREAD

**Issue by hadley** [hadley/mastering-shiny#14]
* shinydashboard
* shiny.semantic
* dull
* shinymaterial
* raw HTML template
* https://github.com/RinteRface/shinyF7

**Comment by iainmwallace** [comment]
A nice collection of alternative UIs https://github.com/RinteRface

**Comment by iainmwallace** [comment]
And this is a great collection of extensions 
https://github.com/nanxstats/awesome-shiny-extensions

**Comment by hadley** [comment]
@iainmwallace thanks for the pointers!
