### ISSUE TITLE
Question regarding Figure 4.11

### ISSUE THREAD

**Issue by MayaGans** [hadley/mastering-shiny#140]
Firstly thanks for this great resource - loving the book so far! I was hoping to gain some clarification on Figure 4.11. The figure doesn't show any relationship between simulation and the other inputs in the graph and I'd like to clarify their relationship graphically.

I tried taking a stab at what this diagram would look like but both still seem a little off to me. 

1. If you change the n/lambda1/lambda2 you still need to click the simulate button in order to see that change reflected in the histogram. 
<img width="797" alt="Screen Shot 2020-02-25 at 7 51 54 AM" src="https://user-images.githubusercontent.com/6053906/75264078-b66b6a00-57a3-11ea-95ad-daaee51b3e78.png">

2. The more I think about it, the arrows are a little circular - you can hit simulate and have the other inputs change. 
<img width="757" alt="Screen Shot 2020-02-25 at 8 04 48 AM" src="https://user-images.githubusercontent.com/6053906/75265275-83c27100-57a5-11ea-88e1-640cbcb9c971.png">

But both these attempts don't seem exactly right to me - any help appreciated!

**Comment by hadley** [comment]
There is no relationship between simulate and the other inputs 😄

**Comment by MayaGans** [comment]
Okay, bear with me, I'm just trying to solidify my mental model by putting this into words

#### Why I thought the two were dependent on one another 🤦‍♀ 
If I change `input$n` to 3, 30, 300 etc, if you squint, it looks like the submit button uses the new `n` as a reactive dependency.

#### But really (maybe)
When I `renderText(input$simulate)` I see the button's input is just a number, iterating + 1. 

So is `eventReactive` dependent on `input$simulate`, but NOT dependent on `input$n` or `input$lambda` (this would explain why just changing `input$n` alone doesn't do anything).

BUT if you change `input$n` and then click `input$simulate` - the button invalidates `eventReactive`, and THEN `x1` & `x2` are recalculated based on the updated `input$n`.

....Is that right? Thanks again for your help and your time!

**Comment by hadley** [comment]
Yes!
