### ISSUE TITLE
Exercise 2.8.5 plot(dataset()) error?

### ISSUE THREAD

**Issue by MayaGans** [hadley/mastering-shiny#142]
When running what I think is the corrected code for Exercise 2.8.5:
```
library(ggplot2)
library(shiny)

datasets <- data(package = "ggplot2")$results[, "Item"]

ui <- fluidPage(
  selectInput("dataset", "Dataset", choices = datasets),
  verbatimTextOutput("summary"),
  plotOutput("plot")
)

server <- function(input, output, session) {
  dataset <- reactive({
    get(input$dataset, "package:ggplot2")
  })

  output$summary <- renderPrint({
    summary(dataset())
  })

  output$plot <- renderPlot({
    plot(dataset())
  })
}
```

If I choose the seals dataset it works, but if I choose another dataset like mtcars I get the error 

```
Warning in data.matrix(x) : NAs introduced by coercion
Warning in data.matrix(x) : NAs introduced by coercion
Warning in data.matrix(x) : NAs introduced by coercion
Warning in data.matrix(x) : NAs introduced by coercion
Warning in data.matrix(x) : NAs introduced by coercion
Warning in data.matrix(x) : NAs introduced by coercion
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning in min(x) : no non-missing arguments to min; returning Inf
Warning in max(x) : no non-missing arguments to max; returning -Inf
Warning: Error in plot.window: need finite 'xlim' values
```

Maybe this is due to the number of factors that are being plotted? I tried splicing the data but this doesn't provide a fix universal to all datasets. Thought you may want to know/consider!

**Comment by julianstanley** [comment]
Same here. The dataset also takes a while to load on my end (similar to [previous similar concerns](https://community.rstudio.com/t/mastering-shiny-chapter-2-exercise-5/49787/3)). 

It's just that some of the datasets are decently large, and some of them are not compatable with `plot()`.

Personally, it makes sense to me to either (1) edit the data source, or (2) just take a few of the datasets. 

For example:

`datasets <- data(package = "ggplot2")$results[, "Item"][c(2, 4, 10)]`

would accomplish the same teaching goal, but those datasets loadly quickly and without errors.

**Comment by hadley** [comment]
Good idea, thanks @julianstanley!
