### ISSUE TITLE
Is the book license ShareAlike or NoDerivatives?

### ISSUE THREAD

**Issue by mpaulacaldas** [hadley/mastering-shiny#158]
The intro says that the book is licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) (*ShareAlike*):

https://github.com/hadley/mastering-shiny/blob/066b8c035c3ebed16983f6c8cdbdbd16656729d8/index.Rmd#L31

But the README says that the book is licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) (*NoDerivatives*), which is more restrictive:

https://github.com/hadley/mastering-shiny/blob/066b8c035c3ebed16983f6c8cdbdbd16656729d8/README.md#L5

I am asking because I have been working through the exercises of the book in my own fork, which I built and deployed via Netlify ([here](https://mastering-shiny-mpc-solutions.netlify.com/basic-app.html#exercises)). As I understand it, what I am doing is OK under a ShareAlike license but would violate a NoDerivatives license because: 

> If you remix, transform, or build upon the material, you may not distribute the modified material.

Anyways, I really don't mind taking down my deployed site (I can still build my version locally), but I thought I should flag the license inconsistencies in case it might become an issue!

**Comment by hadley** [comment]
Yeah, sorry for the confusion, it is ND 😞

**Comment by mpaulacaldas** [comment]
No problem! I will take down my version :slightly_smiling_face:
