### ISSUE TITLE
Process demystifying reactivity feedback

### ISSUE THREAD

**Issue by hadley** [hadley/mastering-shiny#16]
[reactivity.pdf](https://github.com/jcheng5/shiny-book/files/3292399/reactivity.pdf)

**Comment by adisarid** [comment]
@hadley I went through the reactivity chapters (4 and 16). The distinction between `reactive()`, `reactiveVal()` and `reactiveValues()` in chapter 16 could be further explored/demystified by adding a summarizing table comparing the types of reactivity. Here is an example (perhaps needs some tuning):

| function        | use when  | Example use |
|:------------- |:-----|:------|
|`render***()`|Direct reactive relationships between inputs of the app to the rendered outputs|...|
|`reactive()`|Allows you to model more complex relationships between inputs before passing them on to outputs.|
|`eventReactive()`|The same as `reactive()`, but depends on an event (such as a button click)|
|`reactiveVal()`|Create a reactive value, with greater flexibility. Allows control over value from anywhere in the app, but can lead to infinite reactive loops. Handle with care (i.e., use `isolate()` when needed)|
|`reactiveValues()`|Same as `reactiveVal()`, but creates multiple values which can be accessed like you would a regular list in R (with the `$` operator)|
