### ISSUE TITLE
bookmarking with Rshiny

### ISSUE THREAD

**Issue by rajkstats** [hadley/mastering-shiny#177]
Hey Hadley, 
Thanks for putting together this amazing book. This was a good read. Though I'm having a hard time understanding bookmarking in shiny. I had gone through few tutorials online but didn't get it. So, I am requesting a code snippet for this book that could explain the fundamentals behind it.  

- How to add/ remove bookmarks?
- How to save bookmarked information on the server-side?

**Comment by hadley** [comment]
Could you explain what's missing in https://mastering-shiny.org/action-bookmark.html ?

**Comment by rajkstats** [comment]
Sure. Let's say the output is coming from an API, given the two inputs from the shiny web app. So, there are multiple outputs as a result thrown by the API. I want to allow the user to bookmark those outputs and maybe store those values in a backend db/server later. So, when the next time user returns on the web app, they should be able to see their bookmarked items. I have looked at examples in the book given the inputs on how you can generate the bookmarking URL and save it on the server. Since the output is dynamic and changes every time given the inputs from API. So, how can I store items from output to some db/server ?. Hope this makes sense.

**Comment by hadley** [comment]
That's a pretty complicated case, so I don't think the chapter will be able to cover it in. But in short, you'll need to store the results from the API in a database or similar, indexed with a unique id. You'd then use that unique id to bookmark by.

**Comment by rajkstats** [comment]
Thanks, @hadley, I really appreciate your comments. I will try this approach.
