### ISSUE TITLE
renderImage() example won't work unless readers clone the repo

### ISSUE THREAD

**Issue by mpaulacaldas** [hadley/mastering-shiny#182]
This is because the app looks for the images in the `puppy-photos/` directory.

https://github.com/hadley/mastering-shiny/blob/229abb961f2549f59f550bea03e5d2cc393eeb02/action-graphics.Rmd#L337

If the book is a package, they maybe these can be stored under `inst/puppy-photos/` and later retrieved via `system.file()`?

(P.S. I loved the pictures 🐶 )

**Comment by hadley** [comment]
I'm imagining that people will clone the repo if they want to run this example. But I haven't thought about this much yet, so it might change in the future as I add more complicated examples.
