### ISSUE TITLE
4.4.6: incomplete exercise?

### ISSUE THREAD

**Issue by julianstanley** [hadley/mastering-shiny#186]
https://mastering-shiny.org/basic-reactivity.html#exercise

Exercise 4.4.6 says:

> Use reactive expressions to reduce the duplicated code in the following simple apps.

At least to me, it isn't clear what "the following simple apps" refers to. Maybe part of this chapter is missing/incomplete, or I'm missing something? 

(And please let me know if it isn't appropriate to post issues for little things like this! I'm still new to GitHub etiquette and just want to be helpful)

**Comment by hadley** [comment]
The apps haven't been written yet.
