### ISSUE TITLE
In 3.3.1 Text regarding `renderPrint`

### ISSUE THREAD

**Issue by ValeriVoev** [hadley/mastering-shiny#200]
In the example we have:
`  output$code <- renderPrint({ 
    summary(1:10) 
  })
`
but then in the text it is said: 

> Note that there are two render functions that can be used with either of the text output functions:
> 
> renderText() which displays text *returned* by the code.
> renderPrint() which displays text *printed* by the code.

However, `summary` doesn't really print anything explicitly (there is no `print` statement). As far as I see, it *returns* the table:

```
x <- summary(1:10)
class(x)
```
#> [1] "summaryDefault" "table"
Created on 2020-05-27 by the reprex package (v0.3.0)

**Comment by hadley** [comment]
The result of `summary()` is implicitly printed. I'll clarify this in the text.

**Comment by hadley** [comment]
BTW I have literally no idea what number a section is, so it would be maximally useful if you'd include a link when you file an issue

**Comment by hadley** [comment]
Also my explanation here was completely wrong, thanks for spotting this problem1
