### ISSUE TITLE
Typo in 6.3.4

### ISSUE THREAD

**Issue by kiinto** [hadley/mastering-shiny#201]
Very minor but in the second to last sentence you have:

> When I try and someone with their app on RStudio community, creating a reprex is always the first thing I do

It should read

> When I try and **help** someone with their app on RStudio community, creating a reprex is always the first thing I do

Edit: Actually, come to think of it. It should probably read:

> When I try **to help** someone with their app on RStudio community, creating a reprex is always the first thing I do

**Comment by hadley** [comment]
For future reference, this sort of fix is easier to do directly — you can just click the edit button in the navbar to create a PR.

**Comment by kiinto** [comment]
Ah good to know. Will do in future, thanks @hadley :)
