### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by julianstanley** [hadley/mastering-shiny#203]
Good morning!

I think the mastering-shiny.org link is broken because of a server error

![image](https://user-images.githubusercontent.com/22749289/83411077-89070b80-a3e5-11ea-9f7b-867a4710f84b.png)

Image from Chrome 83.0.4103.61/64bit/ubuntu on June 1, 2020. Reproduced on Firefox 76.0.1 and IOS safari.

**Comment by hadley** [comment]
Fixed now, thanks for the report!
