### ISSUE TITLE
Any specific reason list() is used instead of tagList()?

### ISSUE THREAD

**Issue by daattali** [hadley/mastering-shiny#204]
I read "Chapter 15 - modules" and noticed that several times UI elements that are meant to be grouped together are returned in a `list()` and not in a `tagList()`. This might happen in other places in the book too.

Is shiny and @jcheng5 / @wch moving away from `tagList`, or was this just an oversight?

**Comment by hadley** [comment]
It's deliberate. I can't speak for Winston and Joe, but I don't see a need to use a `tagList()` when a `list()` will do.

**Comment by daattali** [comment]
From experience, list doesn't always do the job. A tagList has  an explicit
class that tell shiny this is going to be UI tags. I've run into cases
where a function expects a shiny tag and it checks if the input receiver is
a shiny tag by looking at the class, and fails on a list.

**Comment by daattali** [comment]
From experience, list doesn't always do the job. A tagList has  an explicit class that tell shiny this is going to be UI tags. There are functions out there that expect this behaviour and are intended to work with shiny tags but not with lists. It doesn't come up in basic simple apps but it can occassionally be problematic.

Perhaps consulting with a a shiny team member would be a good idea before ommitting a common shiny practice/rushing to close this issue. Since this is a book that's designed to teach people how to use shiny and not just a random blog or tweet, it'd be best if it teaches all the best practices and doesn't get people acquianted with the wrong functions.

To demonstrate that there are functions that expect to work with tag list but not with list, the simplest example I can think of is the print function:

```
library(shiny)
tags <- tagList(textInput("foo", "foo", "foo"))
print(tags, browse = TRUE)
```

The `browse` param gets auto-completed and browse deals with it nicely. This is not the case with `list()`.
 
Another example I thought of while writing this is `as.character()`:

```
as.character(textInput("foo", "foo", "foo"))
```

is identical to 

```
as.character(tagList(textInput("foo", "foo", "foo")))
```

But if you try using `list()` instead you'll get something that isn't at all what you want.

**Comment by daattali** [comment]
@wch @jcheng5 I'm sorry to summon you into a semingly unimportant discussion. The way I see it, this book will likely become the de facto documentation for shiny, so if it recommends using something that isn't optimal and can in some cases cause bugs, it will save many many man-hours over time by avoiding such recommendations. If this book says to use `list()` and every new shiny developer uses lists, and 1/100 of them run into issues that are fixed by tagList, why not suggest using tagList to begin with?

I'd love your thoughts. Maybe tagList is seen as unnecessary by the shiny team too

**Comment by hadley** [comment]
@daattali I would appreciate if you would leave this issue lie. I am already in frequent communication with Winston and Joe, and I find your comments here to be quite patronising. If you could please leave me alone for a bit, I will be able to divorce my current frustration with you from the technical decision at hand.

**Comment by daattali** [comment]
I'm purely discussing the issue at hand here, please leave out personal feelings and opinions.

Can we at least re-open the issue? You said you "don't see a need" so I replied giving an example of when it's needed. I understand if you have no time to give this any thought right now. You don't have to address it immediately, but if you can't deal with it right now then let's have it open so that you/someone else can reevaluate at a later time.

**Comment by jcheng5** [comment]
Just to make sure we all remain friends, I'm unilaterally locking this thread for 24 hours. See you tomorrow.
