### ISSUE TITLE
Typo in Figure 4.6

### ISSUE THREAD

**Issue by restonian** [hadley/mastering-shiny#205]
In numericInput labels, lambda1 is repeated twice. Should be:
lambda1
lambda2
n
Same issue carried through into Figure 4.9.

**Comment by hadley** [comment]
I don't see this problem:

<img width="829" alt="Screenshot 2020-06-03 at 5 30 43 PM" src="https://user-images.githubusercontent.com/4196/83695577-f4a4d080-a5bf-11ea-9fdf-545a917823ff.png">
