### ISSUE TITLE
6.1.1 Creating the app

### ISSUE THREAD

**Issue by ValeriVoev** [hadley/mastering-shiny#206]
Footnote number 14 leads to a weird place:

> If you already have your future app.R open, type shinyapp then press Shift + Tab to insert the Shiny app snippet^14

leads to

> dplyr::filter() is inspired by base::subset(). subset() uses data-masking, but not through tidy evaluation, so unfortunately the techniques discussed in this chapter don’t apply to it.↩︎

**Comment by hadley** [comment]
Link https://mastering-shiny.org/action-workflow.html#creating-the-app

**Comment by ValeriVoev** [comment]
In fact all footnotes seem to be messed up, and in the next chapter as well ... not sure how long the problem extends to.

**Comment by hadley** [comment]
Should be fixed with the dev version of bookdown.
