### ISSUE TITLE
Suggest to include explanation of `clickOpts` in 7.1.2

### ISSUE THREAD

**Issue by ValeriVoev** [hadley/mastering-shiny#208]
EDIT: Since I now see that `clickOpts` is mentioned in the next section (7.1.3), I would suggest just not using it here in this example since it is not needed for this particular example and may confuse the reader (as it did in my case).

In **7.1.2 Clicking** there are 2 examples for `nearPoints` - one with base plot and one with ggplot. However, the first one (base plot) uses `plotOutput("plot", click = clickOpts("click"))` and the second one uses `plotOutput("plot", click = "plot_click")`.

Should they behave differently? And if yes, what is the role of `clickOpts`?

**Comment by hadley** [comment]
I think this was just a remnant of a previous organisation of the chapter; thanks for pointing it out!
