### ISSUE TITLE
Report: wrong screenshot

### ISSUE THREAD

**Issue by ShixiangWang** [hadley/mastering-shiny#21]
Dear authors:

I find the first figure in the https://mastering-shiny.org/basic-reactivity.html#controlling-timing-of-evaluation is wrong

![image](https://user-images.githubusercontent.com/25057508/62409861-2e0f5700-b610-11e9-8cc1-45b627896094.png)

It is not consistent with the reactive graph

![image](https://user-images.githubusercontent.com/25057508/62409871-513a0680-b610-11e9-9ded-f28c0b17b22f.png)

Please check it.

Best,
Shixiang

**Comment by hadley** [comment]
Note to self: the screenshot is out of date because it uses a function defined elsewhere, and `makeApp()` currently has no way to handle. Might be better to switch to approach in case study.

**Comment by hadley** [comment]
Fixed now
