### ISSUE TITLE
Fig 10.1 looks quite odd

### ISSUE THREAD

**Issue by ValeriVoev** [hadley/mastering-shiny#216]
It seems that the visual rendering of the slider doesn't adjust well to `updateSliderInput` - notice how the tick label at 1 is not aligned with the slider "button" (the round thingy you drag back and forth) at 1:

... in the middle plot, the distance between 0 and 1 seems to be the same as the distance between 1 and 3!

<img width="759" alt="image" src="https://user-images.githubusercontent.com/28623429/84062766-26eb6f00-a9c0-11ea-94ee-0dcfef56e677.png">

The [app](https://hadley.shinyapps.io/ms-update-basics/) itself behaves like this as well. Might need to be raised as a `shiny` issue.

**Comment by hadley** [comment]
Looks like this issue: https://github.com/rstudio/shiny/issues/2254
