### ISSUE TITLE
Fig 10.2 related to 10.1.1 Simple uses - rightmost plot incorrect

### ISSUE THREAD

**Issue by ValeriVoev** [hadley/mastering-shiny#218]
After clicking reset (the sub image to the right in Fig 10.2), the sliders should look like "onload" but they don't. I couldn't find an issue in the code that generates the 3 images:

https://github.com/hadley/mastering-shiny/blob/cf3bef5e0a31845291d9e15438c859740ba1b561/action-dynamic.Rmd#L86

However the image in demos/update-reset/reset.png is indeed the wrong one.

**Comment by hadley** [comment]
I think there's something subtly wrong with my screenshoting code; I have it on my to do list to look into in more detail in the future.
