### ISSUE TITLE
Modules: Repeated use of `NS(id, x)` instead of defining it once

### ISSUE THREAD

**Issue by daattali** [hadley/mastering-shiny#230]
In the modules chapter, every UI function that needs to use a namespaced ID is given the entire NS function every time. For example:

```
histogramUI <- function(id) {
  tagList(
    selectInput(NS(id, "var"), "Variable", names(mtcars)),
    numericInput(NS(id, "bins"), "bins", 10, min = 1),
    plotOutput(NS(id, "hist"))
  )
}
```

The convention is to define `ns <- NS(id)` which then simplifies the rest of the UI calls to simply `ns("var")` etc.

Is the next version of modules discouraging the old way of using `ns <- NS(id)`, or should this be fixed in the book?

**Comment by hadley** [comment]
I think understanding modules is tough enough without adding requiring that you understand function factories so I've stuck with regular function calls throughout this chapter.
