### ISSUE TITLE
Why use vapply below instead of simpler sapply (in the Modules chapter)?

### ISSUE THREAD

**Issue by ValeriVoev** [hadley/mastering-shiny#240]
In this line:

https://github.com/ValeriVoev/mastering-shiny/blob/77898a903832a9a94ff7d781c3f5b510a550bfeb/scaling-modules.Rmd#L196

we have 

`names <- names[vapply(data, filter, logical(1))]`. Why not much simpler
`names <- names[sapply(data, filter)]`

**Comment by hadley** [comment]
Because I never use `sapply()` inside a function, because you don't know what it's going to return.
