### ISSUE TITLE
Ch 4.4 copy and paste issue

### ISSUE THREAD

**Issue by lmadsenbc** [hadley/mastering-shiny#241]
I was trying to recreate the code in CH4.4, but saw error's after copy and pasting.

(Also, I may be bit slow, but could you consider explicitly stating where to define functions in an app.R file (i.e. histogram() and ttest() ) for best practices. Thanks)

Copying the following ui code over from chrome to RStudio ;
`      "Distribution 1",
      numericInput("n1", label = "n", value = 1000, min = 1),
      numericInput("mean1", label = "µ", value = 0, step = 0.1),
      numericInput("sd1", label = "σ", value = 0.5, min = 0.1, step = 0.1)`

I had errors when I ran the code, specifically:
`
Warning in readLines(file, warn = FALSE) :
  invalid input found on input connection 'C:\Users\-----/app.R'
Error in parse(file, keep.source = FALSE, srcfile = src, encoding = enc) : 
  C:\Users\------/app.R:30:42: unexpected INCOMPLETE_STRING
29:            numericInput("n1", label = "n", value = 1000, min = 1),
30:            numericInput("mean1", label = "
                                             ^
`

The Greek letters seem to be a problem, as it ran fine when I replaced them.

Windows 10
Rstudio 1.3.959
Chrome 83.0.4103.116

**Comment by hadley** [comment]
The code works fine for me, so it's likely to be a windows problem.
