### ISSUE TITLE
I am confused by this bullet point (See link below)

### ISSUE THREAD

**Issue by ValeriVoev** [hadley/mastering-shiny#244]
https://github.com/hadley/mastering-shiny/blob/1610eb7615648cb86fae23eb5ddbb2595f2383dc/scaling-packages.Rmd#L43

Why do I need to add a new `app.R`? How can I add a new `app.R` if I already have one? How to "tell" the deployment server how I want to deploy my app? And finally, it is not clear how to load the code with `pkgload` - just running `myApp()` as the code block suggest is what I would normally do (without `pkgload`).

**Comment by hadley** [comment]
This chapter is still very raw; I don't think feedback is useful at this point as it will all be substantially rewritten.
