### ISSUE TITLE
Wrong link in Table of Contents

### ISSUE THREAD

**Issue by woodspock** [hadley/mastering-shiny#247]
Table of Contents link for _7.6 Exercises_ is "https://mastering-shiny.org/basic-app.html#exercises"
Should be  "https://mastering-shiny.org/action-graphics.html#exercises"

**Comment by woodspock** [comment]
I found many similar mistaken links for these paragraphs : 3.1, 3.2.8, 4.1, 4.3.6, 5.1, 5.8,, 7.6, 8.5, 9.2.1, 9.3, 9.4, 10.1.5, 10.2.3, 10.3.4, 11.3, 14.4, 15.6, 17.2, 17.4.2, 20.1, 20.2.4, 22, 23.1, 23.3, 24.1

Looks to me it happens whenever the paragraph label was already used in a previous paragraph

**Comment by hadley** [comment]
Fixed now with bookdown update.
