### ISSUE TITLE
Include info on running shiny app as a background job

### ISSUE THREAD

**Issue by dgkeyes** [hadley/mastering-shiny#25]
Prompted by this discussion on [Twitter](https://twitter.com/thomas_mock/status/1161394109870956544), here's an issue to remind you to include info on running shiny app as a background job. [This video](https://resources.rstudio.com/webinars/joblauncher) has a demonstration of how to do this at 34:02.

**Comment by jthomasmock** [comment]
Also here is the direct link to James's [code](https://github.com/sol-eng/background-jobs/tree/master/shiny-job) and [slides](https://github.com/rstudio/webinars/tree/master/74-background-jobs).

**Comment by hadley** [comment]
There's now at least a mention in the [workflow chapter](https://mastering-shiny.org/action-workflow.html) and I'm hoping it'll be easier in a future version of RStudio: <https://github.com/rstudio/rstudio/issues/5190>
