### ISSUE TITLE
10.3.2 Dynamic filtering examples do not work for Species filtering using factor vector

### ISSUE THREAD

**Issue by juandering** [hadley/mastering-shiny#273]
From the three example codes, reactive changes in Species selection works only with selectInput option selectize = FALSE..

If this option is not so set -- no combination of choices selected for Species will result in a reactive response or update. Only the initial session entry call to filter_var seem to activate. Changing other input sliders resets the Species to nothing selected visual-wise, internally it seems to be all choices selected. always.

For your kind review and comments please. What version information do I need to provide, if so required?

**Comment by hadley** [comment]
Can you please explain the problem in a bit more detail?

**Comment by hadley** [comment]
Closing for now, but if you have more details, I'm happy to look into more detail.

**Comment by youngroklee-ml** [comment]
@hadley  I also experience the same issue, and here are some details. I hope this helps. By the way, it is in section 10.3.3, for Figure 10-11.

In `make_ui()` function, a call of `selectInput()` create a multiselect, but it does not filter data based on the selection.
`selectInput(var, var, choices = levs, selected = levs, multiple = TRUE)`
<img width="883" alt="selectize=TRUE" src="https://user-images.githubusercontent.com/30917347/159602606-b1f71e52-8393-45e6-b838-89671141bdbc.png">

When I call `selectInput()` with `selectize = FALSE` as @juandering suggested, the multiselect correctly performs filtering. Thank you, @juandering !!
`selectInput(var, var, choices = levs, selected = levs, multiple = TRUE, selectize = FALSE)`
<img width="891" alt="selectize=FALSE" src="https://user-images.githubusercontent.com/30917347/159602406-f164758f-c5ec-406b-9aba-8ef78ffbb1c5.png">
