### ISSUE TITLE
Mention how to freeze inputs

### ISSUE THREAD

**Issue by hadley** [hadley/mastering-shiny#293]
https://github.com/rstudio/shiny/pull/3055

**Comment by hadley** [comment]
Probably somewhere in https://mastering-shiny.org/action-dynamic.html#updating-inputs

**Comment by hadley** [comment]
cf https://engineering-shiny.org/common-app-caveats.html

cc @malcolmbarrett

**Comment by malcolmbarrett** [comment]
Oh, that would be great to add. I didn't know about this.

**Comment by hadley** [comment]
In 

```R
ui <- fluidPage(
  dateInput("date", "choose a date"), 
  selectInput("year", "Choose a year", choices = 2010:2030)
)

server <- function(input, output, session) {
  observeEvent(input$date, {
    year <- format(input$date, "%Y")
    message("Changing year to ", year)
    updateSelectInput(inputId = "year", selected = year)
  })
  
  observeEvent(input$year, {
    date <- as.Date(ISOdate(input$year, 1, 1))
    message("Changing date to ", date)
    updateDateInput(inputId = "date", value = date)
  })
}
```

The key problem is that all updates processed by the browser in a single batch, after all observers have completed. This means that it since it starts in an inconsistent state it rapidly toggles back and forward. The easiest fix is to just set `selected = 2021`.
