### ISSUE TITLE
Code in Section 14.2 won't run

### ISSUE THREAD

**Issue by hsm207** [hadley/mastering-shiny#298]
The [code ](https://github.com/hadley/mastering-shiny/blob/7afe4055e17147ddb6276d55466fed5ad621576c/reactivity-tracking.Rmd#L36-L55)in section 14.2 A step-by-step tour of reactive execution won't run because the function `two_a` is not defined.

**Comment by hadley** [comment]
Fixed now that I'm actually using the app to generate a reactlog screenshot: https://mastering-shiny.org/reactive-graph.html#the-reactlog-package
