### ISSUE TITLE
Histogram in Figure 4.2 inconsistent with inputs

### ISSUE THREAD

**Issue by bklingen** [hadley/mastering-shiny#309]
The histogram in Figure 4.2 seems inconsistent with the inputs of the shiny app. The inputs show equal sample sizes for n1 and n2, yet the histogram shows a sample for x1 that is about twice as large as the one for x2. Either change the values shown in the inputs for n1 and n2 to 1000 and 500, respecively, or update Figure 4.2 to show two histograms that are more-or-less overlapping.

**Comment by edovtp** [comment]
I think that that is the idea of the code, since it never states to separate both histograms, only saying `fill = g`, so it stacks both histograms, and to see that they are somewhat equal the colored bars must be of the same length, not that they overlap.

To get an overlapping you should change the position argument in the histogram geom by adding position = "identity". Another way is to use position = "dodge", but I think that it looks messy that way.

Hope that helps

**Comment by bklingen** [comment]
Thanks, yes, neither `position='identity'` or `position='dodge'` seems satisfying. I think when one interprets a histogram, one looks at the height of the bar to see the count in the corresponding bin, and one will not realize that this is the combined count.

For this example, I believe two separate histograms would be better, without losing any of the reactivity features that this example is trying to illustrate. (The only downside is the slightly longer ggplot code.) So, I would suggest the following `histogram` function:
```{r}
histogram <- function(x1, x2, binwidth = 0.1, xlim = c(-3, 3)) {
  df <- data.frame(
    x = c(x1, x2),
    g = c(rep("x1", length(x1)), rep("x2", length(x2)))
  )
  
  ggplot(df, aes(x, fill=g)) +
    geom_histogram(binwidth = binwidth) +
    guides(fill="none") +
    coord_cartesian(xlim = xlim) +
    facet_wrap(vars(g), ncol=1)
}
```
![image](https://user-images.githubusercontent.com/4784206/103704907-1e6c0e80-4f78-11eb-9f61-e3ebcbbc8d7d.png)

**Comment by hadley** [comment]
If the current display is confusing, I think I'd rather switch to frequency polygons; that makes it slightly easier to compare the two distributions.

**Comment by bklingen** [comment]
Yes, from ggplot help: "Frequency polygons are more suitable when you want to compare the distribution across the levels of a categorical variable." :)
