### ISSUE TITLE
Add ui component to section 4.6 example

### ISSUE THREAD

**Issue by bloyal** [hadley/mastering-shiny#338]
Section 4.6 includes example code that describes how to use `observeEvent` to print a message to the console when an input is changed. This code corresponds to the example "Greeting" app in sections 4.2 and 4.3. However, sections 4.4 and 4.5 focus instead on a "Histogram" app. It might be helpful in section 4.6 to also include the `ui` component in the example code, otherwise readers may try to run the new "Greeting" `server` code with the "Histogram" `ui` code (Like I did!)

**Comment by hadley** [comment]
Good catch — I must've restructured the chapter at some point and forgot to repeat the `ui`.
