### ISSUE TITLE
a minor bug in section 8.3.1

### ISSUE THREAD

**Issue by arashHaratian** [hadley/mastering-shiny#341]
the example app in section 8.3.1 has a minor bug. that is if you press the button for the first time, the number will be generated but afterwards if you just change the number of the steps, another number will be generated.

I think it's better to use `eventReactive` instead of [`reactive`](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/action-feedback.Rmd#L424).

**Comment by hadley** [comment]
Good catch, thanks!
