### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by arashHaratian** [hadley/mastering-shiny#342]
I found some typos:

* the `temp_f` has the value  50 not [`75.6`](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/reactivity-motivation.Rmd#L54)

* "single" not ["singe"](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/reactivity-foundations.Rmd#L26)

* additional parenthesis in [section 15.3.4](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/reactivity-foundations.Rmd#L265) 

* "union" not ["unnion"](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/reactivity-escaping.Rmd#L155)

* the code in section 19.4.3 did not work because of difference between ["filterUI"](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/scaling-modules.Rmd#L960) and ["filterUi"](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/scaling-modules.Rmd#L888)

* "summaryOutput" not ["summaryOuput"](https://github.com/hadley/mastering-shiny/blob/2b1788722e4219df205216ca2d8b70d2c08c0321/scaling-modules.Rmd#L1075)

**Comment by hadley** [comment]
Thanks — please feel free to fix directly in a PR.
