### ISSUE TITLE
Missing words in exercise 10.2.3.2

### ISSUE THREAD

**Issue by edovtp** [hadley/mastering-shiny#349]
Hello, in exercise 10.2.3.2 it says 

> Create that allows the user to select from geom_smooth(), geom_histogram(), or geom_point()

perhaps it should be Create an app that ...?

**Comment by JunbinYan** [comment]
unsubscribe
| |
严峻彬
|
|
yanjunbin1102@163.com
|
签名由网易邮箱大师定制
On 12/28/2020 20:23，Eduardo Vásquez<notifications@github.com> wrote：

Hello, in exercise 10.2.3.2 it says

Create that allows the user to select from geom_smooth(), geom_histogram(), or geom_point()

perhaps it should be Create an app that ...?

**Comment by edovtp** [comment]
I'm sorry, I just noticed that this was addressed in PR #345
