### ISSUE TITLE
Typo in 7.2

### ISSUE THREAD

**Issue by hypercompetent** [hadley/mastering-shiny#35]
Thanks for this great book!

I spotted the following minor typo in section 7.2:

"Expressions and outputs should update whenever one of **there** input values changes. This ensures that input and output stay in sync."

https://github.com/hadley/mastering-shiny/blob/0b236cfe5a585700ca36a2b4442c0aa4c277542a/reactivity-motivation.Rmd#L21

Cheers,
-Lucas

**Comment by fran496** [comment]
Hi Lucas, should I make the pull request to fix it? :smile:

**Comment by hadley** [comment]
A PR would be great — there's not really much point in filing an issue for typos since it's a lot of work for little gain.
