### ISSUE TITLE
Live example in 10.1.2 not working

### ISSUE THREAD

**Issue by edovtp** [hadley/mastering-shiny#357]
Hello! the [live example](https://hadley.shinyapps.io/ms-update-nested) of section 10.1.2 Hierarchical select boxes is not working 

![Screenshot from 2021-01-13 20-30-01](https://user-images.githubusercontent.com/47468525/104525239-7b05a400-55de-11eb-8db2-487b2c4c7525.png)

Edit: the live examples of 10.3.1, [render-palette](https://hadley.shinyapps.io/ms-render-palette/), [render-palette-full](https://hadley.shinyapps.io/ms-render-palette-full/), and [filtering-final](https://hadley.shinyapps.io/ms-filtering-final) from 10.4.2 also aren't working.

**Comment by hadley** [comment]
Need to figure out why rsconnect is not autodetecting the needed packages.

**Comment by hadley** [comment]
Problem is that my script uses `lapply(`_packages`, library, character.only = TRUE)`
