### ISSUE TITLE
Data access in Chapter 5

### ISSUE THREAD

**Issue by anelda** [hadley/mastering-shiny#362]
Hallo,

I'm wondering if it may be useful to change the code where data is read in 5.2 as explained below.

Current data read code:

`injuries <- vroom::vroom("neiss/injuries.tsv.gz")`
`products <- vroom::vroom("neiss/products.tsv")`
`population <- vroom::vroom("neiss/population.tsv")`

This relies on having created a local folder `neiss` containing the data. This step is not explained in the setup of the chapter or book.

May it make more sense to change it as follows:

`injuries <- vroom::vroom("https://raw.githubusercontent.com/hadley/mastering-shiny/master/neiss/injuries.tsv.gz")`
`products <- vroom::vroom("https://raw.githubusercontent.com/hadley/mastering-shiny/master/neiss/products.tsv")`
`population <- vroom::vroom("https://raw.githubusercontent.com/hadley/mastering-shiny/master/neiss/population.tsv")`

Or is there a better way to get access to the data? I'm thinking people newish to R and Github my be tripped up by this step.

I'd be happy to submit a PR if you think this can work?

Thanks,
Anelda

**Comment by hadley** [comment]
I'd rather describe how to get the data, maybe early in the introduction?

**Comment by anelda** [comment]
Hi Hadley,

Thanks for your quick response. 

Would the following workflow be good:

- the data for this chapter is stored in the Mastering Shiny Github repository in the [`neiss`](https://github.com/hadley/mastering-shiny/tree/master/neiss) directory
- for the rest of the code to work, you'll need to create a new folder to store the data called `neiss`
- create this folder in your project repository either from the commandline, your file manager, or RStudio's Files pane
- download the data files from the following links and ensure they are stored in the `neiss` folder:
  - https://github.com/hadley/mastering-shiny/raw/master/neiss/injuries.tsv.gz
  - https://raw.githubusercontent.com/hadley/mastering-shiny/master/neiss/population.tsv
  - https://raw.githubusercontent.com/hadley/mastering-shiny/master/neiss/products.tsv

Then the rest of the code should work? Is there a better way?

**Comment by hadley** [comment]
Rather than telling people to create a directory and download the files, I'd suggest just providing the code to do it (e.g. with `dir.create()` and `download.file()`). Otherwise, sounds like a good plan.
