### ISSUE TITLE
could not find function "consoleReactive"

### ISSUE THREAD

**Issue by DanChaltiel** [hadley/mastering-shiny#37]
Hi Hadley,

First, thanks for this awesome book, I learned a gazillion things!

In chapters 7 and 10, you use the `consoleReactive(TRUE)` statement, but I could not find this function anywhere, even in shiny github repo or in google search.

From where am I supposed to import it?

**Comment by hadley** [comment]
It's here: https://github.com/hadley/mastering-shiny/blob/master/common.R#L69-L77

It'll get pulled out somewhere more public in due course.
