### ISSUE TITLE
Can't access dataset for Ch. 5 case study?

### ISSUE THREAD

**Issue by mjsutterer** [hadley/mastering-shiny#38]
Hi, 

I'm trying to work through the Chapter 5 case study, but I can't seem to access the neiss/injuries.tsv.gv referenced.

Specifically, running 

injuries <- vroom::vroom("neiss/injuries.tsv.gz")

in the console returns evaluation errors about the file not existing. Did I miss a step about how the data is supposed to be downloaded/set-up for this case study?

Apologies if I'm missing something obvious.

**Comment by hadley** [comment]
You'll need to download it from https://github.com/hadley/mastering-shiny/blob/master/neiss/injuries.tsv.gz

This will probably be hosted elsewhere when the book is closer to being complete.
