### ISSUE TITLE
General suggestion: pull out tips/best practices 

### ISSUE THREAD

**Issue by kitmacleod** [hadley/mastering-shiny#381]
I love your books, Hadley - amazing. Based on your advice I am working through "The pragmatic programmer". In all books e.g. r4ds, ggplot2, and Mastering Shiny, then there are lots of excellent tips/best practices that are hidden in the main text. Is there an efficient and effective way to extract them like in TPP.

**Comment by hadley** [comment]
No, sorry, and unfortunately I think we're too late in the process to add something now.
