### ISSUE TITLE
16.2 reactlog demo is inaccurate. Observer -> reactiveVal alterations are recorded.

### ISSUE THREAD

**Issue by schloerke** [hadley/mastering-shiny#398]
> Figure 16.2 shows the reactive graph for this example. Again note that the reactive graph does not include any connection from the observers back to the reactive value n.

Fig 16.2: https://mastering-shiny.org/reactivity-components.html#fig:button-graph

Because the _update_ method is not going through the browser, Shiny is recording that the observer is updating the reactiveVal `n`.

![Screen Shot 2021-02-11 at 11 36 25 AM](https://user-images.githubusercontent.com/93231/107667350-7ffd5800-6c5d-11eb-8ad1-a9c5cbdb6863.png)

If it was a `updateNumericInput()` call (which works by updating the input value via the browser), then the diagram provided is accurate.

**Comment by hadley** [comment]
I think what I'm trying to say is that they don't take a reactive dependency. But the more I re-read it, the more confused I get.

**Comment by hadley** [comment]
Maybe this just needs a footnote indicating that they're drawn by reactlog, but don't actually affect the reactive graph as described in https://mastering-shiny.org/reactive-graph.html
