### ISSUE TITLE
https://hadley.shinyapps.io/ms-waiter/ contains the wrong app

### ISSUE THREAD

**Issue by d-morrison** [hadley/mastering-shiny#537]
Link appears in chapter 8; seems like the wrong app got deployed.

**Comment by youngroklee-ml** [comment]
I also see the same issue. I think https://hadley.shinyapps.io/ms-waiter is supposed to show waiter package example, but it currently shows an app that illustrate dynamic height and width that is the same to https://hadley.shinyapps.io/ms-resize/

**Comment by youngroklee-ml** [comment]
It is fixed now! Thank you, Hadley!
