### ISSUE TITLE
broken link to Shiny cheatsheet

### ISSUE THREAD

**Issue by amantaya** [hadley/mastering-shiny#567]
Link to Shiny cheatsheet seems to be broken. 404 error.

https://github.com/hadley/mastering-shiny/blob/718db20ff330397c00806bee4c2eb81fcee13c28/basic-app.Rmd#L250

**Comment by evgeny-vlasov** [comment]
Another broken link in line 329:
`-   You can make your own functions to generate Bootstrap components that Shiny doesn't provide, as explained in "[Utility classes](https://rstudio.github.io/bslib/articles/theming.html#utility-classes)".`

**Comment by nav9** [comment]
I came here to report the cheatsheet broken link. Howcome nobody resolved this issue yet?

**Comment by hadley** [comment]
Fixed now 😄
