### ISSUE TITLE
Broken link to Neiss dataset

### ISSUE THREAD

**Issue by msmith01** [hadley/mastering-shiny#588]
On the following[ page ](https://mastering-shiny.org/basic-case-study.html) there is a link in the code:

```
download <- function(name) {
  url <- "https://github.com/hadley/mastering-shiny/raw/master/neiss/"
  [download.file](https://rdrr.io/r/utils/download.file.html)([paste0](https://rdrr.io/r/base/paste.html)(url, name), [paste0](https://rdrr.io/r/base/paste.html)("neiss/", name), quiet = TRUE)
}
```

The link is broken. 

It should be:

`https://github.com/hadley/mastering-shiny/tree/main/neiss`

Not 

`https://github.com/hadley/mastering-shiny/raw/master/neiss/`.

Additionally, `injuries <- vroom::[vroom](https://vroom.r-lib.org/reference/vroom.html)("neiss/injuries.tsv.gz")` doesn't read in correctly.

**Comment by SprengelLeo** [comment]
change link to https://raw.githubusercontent.com/hadley/mastering-shiny/main/neiss/"

**Comment by mathgorilla** [comment]
I think "https://github.com/hadley/mastering-shiny/tree/main/neiss/" is the correct link but even after using that, I can't seem to use the code listed to open those files.  The tsv files look like html or something like that as opposed to a tsv file.  Is anyone else experiencing this?

**Comment by jialinx007** [comment]
I have the same issue as @mathgorilla. Even after updating the link to https://github.com/hadley/mastering-shiny/tree/main/neiss/. The vroom runs into errors about delim. I tried a few different delim options such as "\t" and " ". It does not read in the data as you show in the ebook (https://mastering-shiny.org/basic-case-study.html) as copied below. 

products <- vroom::[vroom](https://vroom.r-lib.org/reference/vroom.html)("neiss/products.tsv")
products
#> # A tibble: 38 × 2
#>   prod_code title                            
#>       <dbl> <chr>                            
#> 1       464 knives, not elsewhere classified 
#> 2       474 tableware and accessories        
#> 3       604 desks, chests, bureaus or buffets

**Comment by iaulike** [comment]
> I think "https://github.com/hadley/mastering-shiny/tree/main/neiss/" is the correct link but even after using that, I can't seem to use the code listed to open those files. The tsv files look like html or something like that as opposed to a tsv file. Is anyone else experiencing this?

Yes. I’m just going to try to get the files from the neiss package: # install.packages("devtools")
devtools::install_github("hadley/neiss")

**Comment by samlin829** [comment]
Hi everyone, as of 18/Dec/2022 the url to the neiss data is `https://github.com/hadley/mastering-shiny/blob/main/neiss/`. Confirmed on my machine to download the data programmatically.

**Comment by JohnCost** [comment]
> > I think "https://github.com/hadley/mastering-shiny/tree/main/neiss/" is the correct link but even after using that, I can't seem to use the code listed to open those files. The tsv files look like html or something like that as opposed to a tsv file. Is anyone else experiencing this?
> 
> Yes. I’m just going to try to get the files from the neiss package: # install.packages("devtools") devtools::install_github("hadley/neiss")

I think that the reason that the tsv files are not as expected is that the link you are using has changed 'raw' to 'tree', as well as 'master' to 'main'. When using curl to download the raw data you need to use the url with raw in the path. In this case "https://github.com/hadley/mastering-shiny/raw/main/neiss/" works forme.
