### ISSUE TITLE
neiss download path in basic-case-study.Rmd broken

### ISSUE THREAD

**Issue by blechturm** [hadley/mastering-shiny#605]
Hi,

the download path to the neiss data is broken. This hack works:

`download <- function(name) {
  url <- "https://raw.githubusercontent.com/hadley/mastering-shiny/5d398fd655775cbcf278dadf46bfc78af2a0cb11/neiss/"
  download.file(paste0(url, name), paste0("./neiss/", name), quiet = TRUE)
}`

Best
Max

**Comment by albertme0308** [comment]
Simplier:
download <- function(name) {
  url <- "https://raw.githubusercontent.com/hadley/mastering-shiny/main/neiss/"
  download.file(paste0(url, name), paste0("neiss/", name), quiet = TRUE)
}

**Comment by PedroMassaro** [comment]
I was having trouble with this thread, but with your code, everything is correct now. Thanks!
