### ISSUE TITLE
URL for neiss data in chapter 5

### ISSUE THREAD

**Issue by rahsan78** [hadley/mastering-shiny#609]
hi,
To access the neiss data in chapter 5 the following URL  is in the book as well as online version of the book. 
given url : https://github.com/hadley/mastering-shiny/raw/master/neiss/

however this throws a 404 error. I can see there has been some changes in the branch. I have used the following and able to download the files.

url used : https://github.com/hadley/mastering-shiny/blob/main/neiss/

may be worth in changing the URL at lease on the online version of the book ?

regards

Mohammad Ahsan

**Comment by ayoraind** [comment]
Totally agree @rahsan78 

In my case (Chapter 4), I had to use 

`https://raw.githubusercontent.com/hadley/mastering-shiny/main/neiss/`

So, the function then looks like this

`download <- function(name) {
  # url <- "https://github.com/hadley/mastering-shiny/raw/master/neiss/"
  url <- "https://raw.githubusercontent.com/hadley/mastering-shiny/main/neiss/"
  download.file(paste0(url, name), paste0("neiss/", name), quiet = TRUE)
}`

**Comment by hadley** [comment]
The correct link is https://github.com/hadley/mastering-shiny/tree/main/neiss, and the book has been updated accordingly.
