### ISSUE TITLE
Chapter 4 - Wrong URL to download data 

### ISSUE THREAD

**Issue by emsing** [hadley/mastering-shiny#617]
In the online version of the book, I was unable to download the NEISS data using the code from the book. The URL: https://github.com/hadley/mastering-shiny/raw/master/neiss/

gave a 404 message. 

I found this URL to work
https://github.com/hadley/mastering-shiny/raw/main/neiss/

**Comment by robertberryuk** [comment]
Awesome, thanks - this was driving me mad

**Comment by rmflight** [comment]
What's weird, is that the source of the page shows the correct URL (using the `main` branch), but the rendered shows the incorrect. 

I think the book just (I know that's not necessarily that simple) needs to be re-rendered and pushed up.

**Comment by RyanGerardHoward** [comment]
Thanks emsing.  That URL was helpful.

**Comment by ayoraind** [comment]
In my case (as stated in issue #609), I had to use

`https://raw.githubusercontent.com/hadley/mastering-shiny/main/neiss/`

So, the function then looks like this

```
download <- function(name) {
  # url <- "https://github.com/hadley/mastering-shiny/raw/master/neiss/"
  url <- "https://raw.githubusercontent.com/hadley/mastering-shiny/main/neiss/"
  download.file(paste0(url, name), paste0("neiss/", name), quiet = TRUE)
}
```

I commented out the url stated in the online version of the book for emphasis.

**Comment by hadley** [comment]
The correct link is https://github.com/hadley/mastering-shiny/tree/main/neiss, and the book has been updated accordingly.
