### ISSUE TITLE
Error Reading NEISS Files

### ISSUE THREAD

**Issue by dtminnick** [hadley/mastering-shiny#636]
I'm getting an error when I try to read the NEISS files after downloading them.

This line...

injuries <- vroom::vroom("./inst/extdata/injuries.tsv.gz")

...produces this error...

Error: Could not guess the delimiter.

Use `vroom(delim =)` to specify one explicitly.

I get the same error when I attempt to read the population and products files.

**Comment by a-damC** [comment]
Hello @dtminnick ,
I had a similar issue. When I looked into the downloaded files they seemed to be html outputs.
I decided to just manually download the raw files from github.

**Comment by celiahein** [comment]
I had the same issue. I also downloaded manually from Github

**Comment by waseem-medhat** [comment]
As of now the issue still exists. I believe this is because the source's `master` branch was renamed to `main` which broke the download URLs. You can change the URL in your code to reflect that as mentioned in #617.

**Comment by hadley** [comment]
The correct link is https://github.com/hadley/mastering-shiny/tree/main/neiss, and the book has been updated accordingly.
