### ISSUE TITLE
Spelling typo in basic-ui chapter

### ISSUE THREAD

**Issue by adisarid** [hadley/mastering-shiny#75]
https://github.com/hadley/mastering-shiny/blob/eed0f646d044c89708f6bf5487b7900c65046264/basic-ui.Rmd#L194

Should be: 

`fileInput()` *requires* special handling on the server side,...

(The word requires is missing).

**Comment by fmsabatini** [comment]
In line 158 the function is incorrectly referenced `checkboxInputGroup()` instead of checkboxGroupInput().
https://github.com/hadley/mastering-shiny/blob/eed0f646d044c89708f6bf5487b7900c65046264/basic-ui.Rmd#L158-L164

**Comment by hadley** [comment]
There's not much point in reporting typos as issues as it's more effort for you to describe and then me to fix as opposed to just clicking the "edit" button and fixing with a PR.

**Comment by adisarid** [comment]
In retrospect, no use submitting issues or PR for small stuff such as typos. Will probably be fixed in the editorial process. But since I already started this, I submitted a PR fixing this issue.

**Comment by hadley** [comment]
PRs are extremely useful because they help everyone reading the book between now and when it's published. Thanks for making one!
