### ISSUE TITLE
Case study chapter for advanced-ui

### ISSUE THREAD

**Issue by DivadNojnarg** [hadley/mastering-shiny#77]
Similar to the first case study (Getting Started section), I would see a slot for a case study in the advanced-ui part. There are a lot of features mentioned in Chapter 12 that would require a practical example to fit with business needs, that is creating a new template From scratch for instance. I can help in the process.

**Comment by DivadNojnarg** [comment]
@hadley : as discussed, an example may be found [here](https://divadnojnarg.github.io/outstanding-shiny-ui/custom-templates-selection.html).

**Comment by hadley** [comment]
To close the loop on this, I think it's increasingly unlikely that "mastering shiny" will include an advanced UI section; instead we'll point to upcoming books on the topic like https://divadnojnarg.github.io/outstanding-shiny-ui/.
