### ISSUE TITLE
Connection between event-driven and object-oriented programming

### ISSUE THREAD

**Issue by cpsievert** [hadley/mastering-shiny#8]
https://github.com/jcheng5/shiny-book/blob/6116549ee9181d761d210a624590d5dde38fcaf4/07-demystifying-reactivity.Rmd#L420

Is this 1st sentence partially a reference to what you've already outlined here (seems like it)?

https://github.com/jcheng5/shiny-book/blob/6116549ee9181d761d210a624590d5dde38fcaf4/07-demystifying-reactivity.Rmd#L54-L86

Either way, it might be useful to draw a connection here.

**Comment by hadley** [comment]
This either has been, or will be, rewritten so I'm going to close this issue.
