### ISSUE TITLE
Explain where the `consoleReactive()` function comes from

### ISSUE THREAD

**Issue by strboul** [hadley/mastering-shiny#86]
It would be nice if you can explain where the `consoleReactive()` function comes. In the book, I see that the function is mentioned in reactivity-related sections, but it's usually placed after `library(shiny)` statement. I find this confusing because that function is not one of the exported functions in Shiny. And there's no reference to the `common.R` file where is the place of this function.

https://github.com/hadley/mastering-shiny/search?q=consoleReactive&unscoped_q=consoleReactive

Or do you have plans to move that function to the Shiny soon?

**Comment by hadley** [comment]
Yes, the plan is to get it into Shiny.

**Comment by strboul** [comment]
Great! Then it may be better to write such a statement after it's added: 
> ... the function `consoleReactive()`, which is available in Shiny version xx or higher, is ...

**Comment by hadley** [comment]
Yes, I will do that when I'm next working on that chapter.
