### ISSUE TITLE
Explain disadvantages of global.R

### ISSUE THREAD

**Issue by adsteen** [hadley/mastering-shiny#87]
Re: `action-modules.Rmd`, line 15: It would be valuable to explain in more detail *why* `global.R` is not the preferred place to put globally-accessible code.

As of October 2019, [several](https://mraess.netlify.com/2018/07/the-awesomeness-that-is-the-global-r-file-or-how-to-clean-up-your-shiny-app/) [pages](https://stevenmortimer.com/tips-for-making-professional-shiny-apps-with-r/#use-a-global.r-file) extolling the virtues of `global.R` appear high on a Google search for `shiny global.R`. This would be a good place to present arguments against `global.R`.

**Comment by adisarid** [comment]
+1 also related to the discouraged use of the ui.R/server.R split in favor of app.R.

**Comment by hadley** [comment]
I don't see any mention `global.R` in the book currently, so I'm going to close this issue.
