### ISSUE TITLE
The people side of deploying an app

### ISSUE THREAD

**Issue by hadley** [hadley/mastering-shiny#96]
Give the reader some sense of how IT folks view the world, and what they are going to worry about when they deploy an app.

**Comment by trestletech** [comment]
- Who's responsible for hosting it?
 - On-call rotations
 - What the boundary/handoff between data scientist and IT looks like 
 - What would IT expect of the data scientists (e.g. revision control, automated tests, etc.)

**Comment by mkrasmus** [comment]
Architecture and security

**Comment by hadley** [comment]
This is now either wrapped up in https://mastering-shiny.org/best-practices.html, or clearly out of scope.
